# Generated by Django 6.0.2 on 2026-02-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("journalist", "Journalist"),
                    ("editor", "Editor"),
                ],
                default="reader",
                help_text="Role of the user: Reader, Journalist, or Editor",
                max_length=20,
            ),
        ),
    ]
