# Generated by Django 6.0.2 on 2026-02-13 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
