# Generated by Django 6.0.2 on 2026-02-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_article_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the article is published (approved).",
                null=True,
            ),
        ),
    ]
